#!/bin/sh

# Shift the focus to another window
riverctl map normal Super H focus-view left
riverctl map normal Super J focus-view down
riverctl map normal Super K focus-view up
riverctl map normal Super L focus-view right

# Shift the window to another window
riverctl map normal Super+Shift H swap left
riverctl map normal Super+Shift J swap down
riverctl map normal Super+Shift K swap up
riverctl map normal Super+Shift L swap right

# Shift the focus to another workspace
riverctl map normal Super+Control H set-focused-tags "$((1 << 0))"
riverctl map normal Super+Control J set-focused-tags "$((1 << 1))"
riverctl map normal Super+Control K set-focused-tags "$((1 << 2))"
riverctl map normal Super+Control L set-focused-tags "$((1 << 3))"

# Shift the window to another workspace
riverctl map normal Super+Shift+Control H set-view-tags "$((1 << 0))"
riverctl map normal Super+Shift+Control J set-view-tags "$((1 << 1))"
riverctl map normal Super+Shift+Control K set-view-tags "$((1 << 2))"
riverctl map normal Super+Shift+Control L set-view-tags "$((1 << 3))"

# Shift the window to another output
riverctl map normal Super+Alt H send-to-output -current-tags left
riverctl map normal Super+Alt L send-to-output -current-tags right

# Close the window
riverctl map normal Super X close

# Exit river
riverctl map normal Super Escape exit

# Toggle fullscreen
riverctl map normal Super F toggle-fullscreen
t
# Raise/Lower the volume
riverctl map normal None XF86AudioRaiseVolume spawn "pactl set-sink-volume '@DEFAULT_SINK@' '+5%'"
riverctl map normal None XF86AudioLowerVolume spawn "pactl set-sink-volume '@DEFAULT_SINK@' '-5%'"

# Mute/Unmute the volume
riverctl map normal None XF86AudioMute spawn "pactl set-sink-mute '@DEFAULT_SINK@' toggle"

# Take a screenshot
riverctl map normal Super S spawn "slurp | grim -g - /home/jack/pictures/screenshots/$(cat /dev/urandom | tr -cd 'a-f0-9' | head -c 8).png"

# Launch apps
riverctl map normal Super Return spawn "alacritty"
riverctl map normal Super I spawn "firefox"
riverctl map normal Super O spawn "vscodium --enable-features='UseOzonePlatform' --ozone-platform='wayland'"
riverctl map normal Super N spawn "thunar"
riverctl map normal Super M spawn "pavucontrol"
riverctl map normal Super Q spawn "qbittorrent"
riverctl map normal Super W spawn "obs"
riverctl map normal Super E spawn "anki"
