#! /bin/sh

bspc monitor -d 1 2 3 4

bspc config border_width 2
bspc config window_gap 10

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config focused_border_color "#89b4fa"
bspc config active_border_color "#313244"
bspc config normal_border_color "#313244"